qwestion/urls.py
from django.urls import path
from . import views
app_name = 'qwestion'
urlpatterns = [
   # и т.д. пишешшь више чем нижняя строка
    path('', views.index, name='index'),
    path('s/<int:pk>/', views.start, name='survey-start'),
    path('survey/<int:pk>/', views.survey_view, name='survey_detail'),
    path('stop/', views.survey_stop, name='survey-stop'),
    path('pause/', views.pause, name='survey-pause'),
]

reports/urls.py
from django.urls import path
from . import views
from .views import RatingCountListView, RatingToXls

app_name = 'reports'
urlpatterns = [
    # path('', index, name='index'),
    path('', RatingCountListView.as_view(), name = 'rating-list'),
    path('xls/', RatingToXls.as_view(), name='xlsTofile'),

    ]

screater/urls.py
from django.urls import path
from .views import *
app_name = 'screater'

urlpatterns = [
    path('', SurveyListView.as_view(), name='survey-list'),
    path('survey/<int:pk>/edit/', SurveyUpdateView.as_view(), name='survey-edit'),
    path('survey/new/', SurveyCreateView.as_view(), name='survey-new'),
    path('qwestion/', QwestionListView.as_view(), name='qwestion-list'),
    path('qwestion/<int:pk>/edit/', QwestionUpdateView.as_view(), name='qwestion-update'),
    path('qwestion/new/', QwestionCreateView.as_view(), name='qwestion-new'),
    path('qwestion/new/answers/', QwestionCreate.as_view(), name='qwestions-answers'),
    path('qwestion/<int:pk>/delete/', QwestionDeleteView.as_view(), name='qwestion-delete'),
    path('answer/', AnswerListView.as_view(), name='answer-list'),
    path('answer/new/', AnswerCreateView.as_view(), name='answer-new'),
    path('answer/<int:pk>/edit/', AnswerUpdateView.as_view(), name='answer-update'),
    path('answer/<int:pk>/delete/',AnswerDeleteView.as_view(), name='answer-delete'),

]

test_app/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls import include, url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('qwestion.urls', 'qwestion'), namespace='qwestion')),
    path('report/', include(('reports.urls', 'reports'), namespace='reports')),
    path('manager/', include(('screater.urls', 'screater'), namespace='screater')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

qwestion/models.py
from django.db import models
from django.contrib.auth.admin import User
from django.urls import reverse


class Survey(models.Model):
    title = models.CharField(max_length=255, verbose_name='Наименование теста')
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=' Автор')
    timedelta = models.IntegerField(default=0, verbose_name='Время выполнения теста')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    public = models.BooleanField(default=False, verbose_name="Опубликовано")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('qwestion:survey_detail', kwargs={"pk": self.id})

    class Meta:
        ordering = ['title', 'created']


class Qwestion(models.Model):
    Q_CHOICES = (
        ('ch', 'checkbox'),
        ('rd', 'radio'),
    )
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, verbose_name='Наименование теста')
    title = models.CharField(max_length=755, verbose_name='Вопрос')
    input = models.CharField(max_length=2, choices=Q_CHOICES, default='ch', verbose_name='Тип поля')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("qwestion:survey-start", kwargs={"pk": self.id})

    class Meta:
        ordering = ['pk']


class Answer(models.Model):
    qwestion = models.ForeignKey(Qwestion, on_delete=models.CASCADE, verbose_name='Вопрос')
    title = models.CharField(max_length=555, verbose_name='Ответ')
    truefild = models.BooleanField(default=False, verbose_name='Правильный ответ')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['pk']


class Rating(models.Model):
    username = models.CharField(max_length=55, db_index=True, verbose_name='Имя пользователя')
    email = models.CharField(max_length=55, verbose_name='Email')
    survey = models.ForeignKey(Survey, on_delete=models.PROTECT, verbose_name='Наменование теста')
    sessionid = models.CharField(max_length=200, db_index=True)
    qwestion = models.ForeignKey(Qwestion, on_delete=models.PROTECT, verbose_name='Вопрос')
    answer = models.CharField(max_length=100, verbose_name='Список номеров ответов пользователя')
    true_answer = models.CharField(max_length=100, verbose_name='Список номеров правильных ответов')
    result = models.BooleanField(default=False, verbose_name='Результат')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')

    def __str__(self):
        return self.sessionid

    class Meta:
        ordering = ['sessionid', '-created']

screater/models.py
from django.db import models

# Create your models here.

screater/forms.py
from django import forms
from django.forms import inlineformset_factory
from qwestion.models import Survey, Qwestion, Answer
from crispy_forms.helper import FormHelper


class SurveyCreateForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Survey
        fields = ['title', 'timedelta', 'public']

    def __init__(self, *args, **kwargs):

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.author = kwargs.pop('user')
        super(SurveyCreateForm, self).__init__(*args, **kwargs)



class AddSurveyForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea)


    class Meta:
        model = Survey
        fields = ['title', 'timedelta', 'public']


# QwestionFormset = inlineformset_factory(Survey, Qwestion, fields='__all__')
AnswerFormset = inlineformset_factory(Qwestion, Answer, fields='__all__', extra=4)


class QwestionForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Qwestion
        fields = ['title', 'input']

class QwestionCreateForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Qwestion
        fields = '__all__'


class AnswerCreateForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Answer
        fields = '__all__'

qwestion/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
# from django.core.signing import Signer
from .form import ContactForm
import uuid

import datetime

from .models import *


# Create your views here.


def index(request):
    """
    Список тестов
    :param request:
    :return:
    """
    survey = Survey.objects.filter(public=True)
    return render(request, 'qwestion/index.html', context={'survey': survey})


def pause(request):
    """
    Отсрочка ответа на вопрос
    :param request:
    :return:
    """
    if request.method == 'POST':
        qwestion_id = request.POST.get("qwestion_id")
        qwestions = list(request.session['qwestions'])
        qwestions.append(qwestion_id)
        qwestions.reverse()
        value = qwestions.pop()
        print(value)
        request.session['qwestions'] = qwestions
        request.session.modified = True

    return HttpResponseRedirect(reverse('qwestion:survey-start', kwargs={'pk': value}))


def start(request, pk):
    """
    Страница вопросов
    :param request:
    :param pk:
    :return:
    """
    if request.method == 'POST':
        sessionid = request.session['sessionkey']
        name = request.session['username']
        email = request.session['email']
        answers = [entry for entry in request.POST.values()][1:-2]
        answers = list(map(int, answers))
        survey_id = request.POST.get("survey_id")
        qwestion_id = request.POST.get("qwestion_id")
        answers_true = list(Answer.objects.filter(qwestion=qwestion_id, truefild=True).values_list('id', flat=True))
        if len(list(set(answers) ^ set(answers_true))) == 0:
            result = True
        else:
            result = False

        rating = Rating(username=name,email=email, survey=Survey.objects.get(pk=survey_id), sessionid=sessionid, qwestion=Qwestion.objects.get(pk=qwestion_id),
                        answer=answers,
                        true_answer=answers_true, result=result)
        rating.save()
        qwestions = list(request.session['qwestions'])
        if len(qwestions) == 0:
            #delete_session(request)
            return HttpResponseRedirect(reverse('qwestion:survey-stop'))

        else:
            value = qwestions.pop()
            request.session['qwestions'] = qwestions
            request.session.modified = True
            return HttpResponseRedirect(reverse('qwestion:survey-start', kwargs={'pk': value}))

    else:
        try:
            request.session['username']
        except:
            return HttpResponseRedirect(reverse('qwestion:index'))
        if stop_time(request):
            return HttpResponseRedirect(reverse('qwestion:survey-stop'))

            #return render(request, 'qwestion/stop.html', context={})
        qwestion = get_object_or_404(Qwestion, pk=pk)
        answers = Answer.objects.order_by('?').filter(qwestion=qwestion)
        mytimer = my_timer(request)
        return render(request, 'qwestion/start.html', context={'qwestion': qwestion, 'answers': answers, 'mytimer': mytimer})


def survey_view(request, pk):
    """
    Страница регистрации пользователей
    :param request:
    :param pk:
    :return:
    """
    form = ContactForm()
    if request.method == "GET":
        survey = get_object_or_404(Survey, pk=pk)
        return render(request, 'qwestion/survey_detail.html', {'survey': survey, 'form': form})

    if request.method == 'POST':
        request.session['username'] = request.POST.get("name")
        request.session['email'] = request.POST.get("email")
        request.session['timedelta'] = request.POST.get("timedelta")
        request.session['start_time'] = str(datetime.datetime.now())
        # signer = Signer()
        # request.session['sessionkey'] = signer.sign(request.POST.get("name") + ':' + request.POST.get("email") + ':' + str(datetime.datetime.now()))
        request.session['sessionkey'] = uuid.uuid4().hex
        survey_id = request.POST.get("surveyId")
        request.session['survey_id']  = survey_id
        qwestions = list(Qwestion.objects.order_by('?').filter(survey__id=survey_id).values_list('id', flat=True))
        value = qwestions.pop()
        request.session['qwestions'] = qwestions
        request.session.modified = True
        # return HttpResponse("UserName: {0} Qwestions: {1} value:{2}".format(request.session['username'], request.session['qwestion'], value))
        return HttpResponseRedirect(reverse('qwestion:survey-start', kwargs={'pk': value}))


def survey_stop(request):
    """
    Формируем последнюю страницу теста- результаты
    :param request:
    :return:
    """
    username = None
    try:

        survey_id = request.session['survey_id']
        sessionid = request.session['sessionkey']
        username =  request.session['username']


    except:
        # return render(request, 'qwestion/stop.html')
        pass

    survey = Survey.objects.get(pk=int(survey_id))
    countQwestion = Qwestion.objects.filter(survey=survey).count()
    rightAnswer = Rating.objects.filter(sessionid=sessionid,result=True).count()
    procent = rightAnswer/countQwestion*100

    delete_session(request)
    return render(request, 'qwestion/stop.html', context={'survey': survey, 'count': countQwestion, 'right': rightAnswer,'procent': procent,
                                                          'username':username})

def delete_session(request):
    """
    Удаляем данные сессии
    :param request:
    :return:
    """
    try:
        del request.session['qwestions']
        del request.session['username']
        del request.session['email']
        del request.session['timedelta']
        del request.session['start_time']
        del request.session['sessionid']
        del request.session['survey_id']
        del request.session['sessionkey']
        request.session.modified = True

    except KeyError:
        pass


def stop_time(request):
    try:
        timedelta = datetime.timedelta(minutes=int(request.session['timedelta']))
        start_time = datetime.datetime.strptime(request.session['start_time'], '%Y-%m-%d %H:%M:%S.%f')
        now = datetime.datetime.now()
        delta = start_time + timedelta

        if delta > now:
            return False
    except:
        return True
        # return render(request, 'qwestion/stop.html', context={})
    # return render(request, 'qwestion/stop.html', context={})
    return True


def my_timer(request):
    """
    Возвращаем время до окончания теста
    :param request:
    :return:
    """
    try:
        timedelta = datetime.timedelta(minutes=int(request.session['timedelta']))
        start_time = datetime.datetime.strptime(request.session['start_time'], '%Y-%m-%d %H:%M:%S.%f')
        now = datetime.datetime.now()
        delta = start_time + timedelta

        if delta > now:
            return delta
    except:
        return 0
        # return render(request, 'qwestion/stop.html', context={})
    # return render(request, 'qwestion/stop.html', context={})
    return 0

screater/templates/screater/add_qwestion.html
{%extends 'base.html'%}
{%block content%}
{% load crispy_forms_tags %}
    <h3>Добавление вопроса</h3>
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
{{ form |crispy }}
 <br>
            <fieldset>
                <legend></legend>
                {{ answer_form.management_form }}
                {{ answer_form.non_form_errors }}
                {% for form in answer_form %}
                    {{ form.id }}
                    <div class="inline {{ qwestion_form.prefix }}">
                        {{ form.title.errors }}
                        {{ form.title.label_tag }}
                        {{ form.title |as_crispy_field }}
                        {{ form.truefild.errors }}
                        {{ form.truefild.label_tag }}
                        {{ form.truefild |as_crispy_field }}

                    </div>


                {% endfor %}
            </fieldset>

 <button class="btn btn-primary" type="submit" name="submit">Добавить</button>
    </form>
{%endblock%}

screater/templates/screater/answer_confirm_delete.html
{% extends "base.html" %}


{% block content %}


<div class="center">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Вы действительно хотите удалить ответ ?
        <br>
        <div class="card">
            <div class="card-body">
             {{object.title}}
             </div>
        </div>
        <br>
        <p>
       <button type="submit" class="btn btn-danger">Удалить</button>
        <a class="btn btn-primary" data-toggle="collapsing"  href="{% url 'screater:qwestion-list' %}" role="button" aria-expanded="false">Отмена </a>
        </p>
    </form>
</div>

{% endblock %}

screater/templates/screater/answer_form.html
{% extends "base.html" %}
{% block title %}Ответ {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Ответ</h1>

<form method="post">{% csrf_token %}
    {{ form |crispy }}
    <input class="btn btn-primary" type="submit" value="Сохранить">
</form>


{% endblock %}

screater/templates/screater/answers.html
{% extends "base.html" %}
{% block title %}Ответы{% endblock %}
{% block content %}

    <h1> Ответы </h1>

<form class="uniForm blueForms" action="" method="get">
        {{ filter.form.as_p }}
        <input class="btn btn-primary" type="submit" />
    </form>


<table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Ответ</th>
        <th scope="col">Правильный ответ</th>
    </tr>
    </thead>
    <tbody>
    {% for s in object_list %}
    <tr>
        <td>{{s.id}}</td>
        <td>{{s.title}}</td>
         <td>{{s.truefild}}</td>

        <td> <form action="{% url 'screater:answer-update' pk=s.id %}"> <button type="submit" class="btn btn-outline-info" >Редактировать</button></form></td>
        <td> <form action="{% url 'screater:answer-delete' pk=s.id %}"> <button type="submit" class="btn btn-outline-danger" >Удалить</button></form></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<hr>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}
          <!-- If it ain't a search result display, don't append the search query
               to the URL. -->
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}&qwestion={{qwestion_id}}" tabindex="-1">Предыдущая</a>
          </li>
          {% else %}
          <!-- Append the searched query to the URL, so that on a search results page,
               the pagination don't revert to listing all the listview items. -->
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}&qwestion={{qwestion_id}}" tabindex="-1">Предыдущая</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Предыдущая</a>
        </li>
        {% endif %}

     {% for l in  page_obj.paginator.page_range %}
    {% if l <= page_obj.number|add:5 and l >= page_obj.number|add:-5 %}
        {% if page_obj.number == l %}
            <li class="page-item active"><a class="page-link" href="?page={{forloop.counter}}&qwestion={{qwestion_id}}">{{forloop.counter}}</a></li>
        {% else %}
           <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}&qwestion={{qwestion_id}}">{{forloop.counter}}</a></li>
        {% endif %}
    {% endif %}
{% endfor %}

        {% if page_obj.has_next %}
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}&qwestion={{qwestion_id}}">Следующая</a>
          </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}&qwestion={{qwestion_id}}">Следующая</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Следующая</a>
        </li>
        {% endif %}
    </ul>
</nav>





{% endblock %}

screater/templates/screater/detail.html
{% extends "base.html" %}


{% block content %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

  {{ forms.survey_form.as_p }}
  <label>qwestion</label>
  {{ forms.qwestion_form.as_p }}
  <label>Background photo</label>
  {{ forms.answer_form.as_p }}
  <input class="btn btn-primary" type="submit" value="submit"/>
</form>
{% endblock %}

screater/templates/screater/qwestion_confirm_delete.html
{% extends "base.html" %}


{% block content %}


<div class="center">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Вы действительно хотите удалить вопрос ?
        <br>
        <div class="card">
            <div class="card-body">
             {{object.title}}
             </div>
        </div>
        <br>
        <p>
       <button type="submit" class="btn btn-danger">Удалить</button>
        <a class="btn btn-primary" data-toggle="collapsing"  href="{% url 'screater:qwestion-list' %}" role="button" aria-expanded="false">Отмена </a>
        </p>
    </form>
</div>

{% endblock %}

screater/templates/screater/qwestion_form.html
{% extends "base.html" %}
{% block title %}Вопрос {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Вопрос</h1>

<form method="post">{% csrf_token %}
    {{ form |crispy }}
    <input class="btn btn-primary" type="submit" value="Сохранить">
</form>


{% endblock %}

screater/templates/screater/qwestions.html
{% extends "base.html" %}
{% block title %}rating{% endblock %}
{% block content %}

    <h1> Вопросы </h1>

<form class="uniForm blueForms" action="" method="get">
        {{ filter.form.as_p }}
        <input class="btn btn-primary" type="submit" />
    </form>


<table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Вопрос</th>
    </tr>
    </thead>
    <tbody>
    {% for s in object_list %}
    <tr>
        <td>{{s.id}}</td>
        <td>{{s.title}}</td>

        <td> <form action="{% url 'screater:qwestion-update' pk=s.id %}"> <button type="submit" class="btn btn-outline-info" >Редактировать</button></form></td>
        <td> <form action="{% url 'screater:qwestion-delete' pk=s.id %}"> <button type="submit" class="btn btn-outline-danger" >Удалить</button></form></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<hr>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}
          <!-- If it ain't a search result display, don't append the search query
               to the URL. -->
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}&survey={{survey_id}}" tabindex="-1">Предыдущая</a>
          </li>
          {% else %}
          <!-- Append the searched query to the URL, so that on a search results page,
               the pagination don't revert to listing all the listview items. -->
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}&survey={{survey_id}}" tabindex="-1">Предыдущая</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Предыдущая</a>
        </li>
        {% endif %}

     {% for l in  page_obj.paginator.page_range %}
    {% if l <= page_obj.number|add:5 and l >= page_obj.number|add:-5 %}
        {% if page_obj.number == l %}
            <li class="page-item active"><a class="page-link" href="?page={{forloop.counter}}&survey={{survey_id}}">{{forloop.counter}}</a></li>
        {% else %}
           <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}&survey={{survey_id}}">{{forloop.counter}}</a></li>
        {% endif %}
    {% endif %}
{% endfor %}

        {% if page_obj.has_next %}
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}&survey={{survey_id}}">Следующая</a>
          </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}&survey={{survey_id}}">Следующая</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Следующая</a>
        </li>
        {% endif %}
    </ul>
</nav>





{% endblock %}

screater/templates/screater/survey_form.html
{% extends "base.html" %}
{% block title %}index {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<h1>Создание теста</h1>

<form method="post">{% csrf_token %}
    {{ form |crispy }}
    <input class="btn btn-primary" type="submit" value="Save">
</form>


{% endblock %}

screater/templates/screater/surveys.html
{% extends "base.html" %}
{% block title %}index {% endblock %}
{% block content %}
    <h1> Выберите тест </h1>

<table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Наименование теста</th>
      <th scope="col">Время выполнения</th>
      <th scope="col">Дата создания</th>
      <th scope="col">Автор</th>
      <th scope="col">Опубликовано</th>
    </tr>
    </thead>
    <tbody>
    {% for s in object_list %}
    <tr>
        <td>{{s.id}}</td>
        <td>{{s.title}}</td>
        <td>{{s.timedelta}}</td>
        <td>{{s.created}}</td>
        <td>{{s.author}}</td>
        <td>{{s.public}}</td>
        <td> <form action="{% url 'screater:survey-edit' pk=s.id %}"> <button type="submit" class="btn btn-outline-info" >Редактировать</button></form></td>
    </tr>
    {% endfor %}
    </tbody>
</table>


{% include 'include/paginator.html'%}
{% endblock %}