reports/urls.py
from django.urls import path
from . import views
from .views import RatingCountListView, RatingToXls

app_name = 'reports'
urlpatterns = [
    # path('', index, name='index'),
    path('', RatingCountListView.as_view(), name = 'rating-list'),
    path('xls/', RatingToXls.as_view(), name='xlsTofile'),

    ]

test_app/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls import include, url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('qwestion.urls', 'qwestion'), namespace='qwestion')),
    path('report/', include(('reports.urls', 'reports'), namespace='reports')),
    path('manager/', include(('screater.urls', 'screater'), namespace='screater')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

reports/models.py
from django.db import models

# Create your models here.

reports/views.py
from django.views import View
from qwestion.models import Rating
from .filter import RatintSurveyFilter
from datetime import datetime
from openpyxl import Workbook
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django_filters.views import FilterView
from django.db.models import Count


# Create your views here.

class RatingCountListView(FilterView):
    """
    Подсчет правльных ответов
    """
    breadcrumbs = ['ratiglist']
    model = Rating
    paginate_by = 25
    filterset_class = RatintSurveyFilter


    template_name = 'report/rating_list.html'

    def get_context_data(self, **kwargs):
        """
        Забираем параметры фильтра из строки запроса
        :param kwargs:
        :return:
        """
        context = super().get_context_data(**kwargs)
        survey = self.request.GET.get('survey','')
        survey = survey.replace(" ", "+")
        context['survey_id']=survey
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        """
        Декорируем диспетчер функцией login_required, чтобы запретить просмотр отображения неавторизованными
        пользователями
        """
        return super(RatingCountListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        """

        Подсчитываем количество правильных ответов с учетом фильтра
        :return:
        """

        object_list = Rating.objects.values('sessionid','username').filter(result=True).order_by('sessionid').annotate(count=Count('id'))

        return object_list


class RatingToXls(View):
    """
    Формируем файл xls для модели Raiting
    """


    def get_context_data(self, **kwargs):
        """
        Забираем параметры фильтра из строки запроса
        :param kwargs:
        :return:
        """
        context = super().get_context_data(**kwargs)
        survey = self.request.GET.get('survey','')
        survey = survey.replace(" ", "+")
        context['survey_id']=survey
        return context


    @method_decorator(login_required)
    def get(self, request):
        ratings = Rating.objects.all()
        survey = self.request.GET.get('survey','')
        if (survey!=''):
            # print(ratings)
            ratings = Rating.objects.filter(survey__pk=int(survey))
            # print(ratings)
        response = HttpResponse(
                content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            )
        response['Content-Disposition'] = 'attachment; filename={date}-raing.xlsx'.format(
                date=datetime.now().strftime('%Y-%m-%d'),
            )
        workbook = Workbook()

            # Get active worksheet/tab
        worksheet = workbook.active

        worksheet.title = 'Результаты тестивания'

            # Define the titles for columns
        columns = [
                'ID',
                'Наименование теста',
                'Имя пользователя',
                'Email',
                'Вопрос',
                'Ответы пользователя',
                'Правильные ответы',
                'Результат',
                'Дата теста',
                'Сессия',
            ]
        row_num = 1

            # Assign the titles for each cell of the header
        for col_num, column_title in enumerate(columns, 1):
            cell = worksheet.cell(row=row_num, column=col_num)
            cell.value = column_title

            # Iterate through all movies
        for rating in ratings:
            row_num += 1

                # Define the data for each cell in the row
            row = [
                    rating.pk,
                    str(rating.survey),
                    rating.username,
                    rating.email,
                    str(rating.qwestion),
                    rating.answer,
                    rating.true_answer,
                    rating.result,
                    rating.created,
                    rating.sessionid,
                ]

                # Assign the data for each cell of the row
            for col_num, cell_value in enumerate(row, 1):
                cell = worksheet.cell(row=row_num, column=col_num)
                cell.value = cell_value

        workbook.save(response)

        return response

reports/templates/report/index.html
{% extends "base.html" %}
{% block title %}index {% endblock %}
{% block content %}
    <h1> Report</h1>
{% for r in rating %}
 {{r.survey}} {{r.created}} {{r.username}} -- {{r.count}}<br>
{% endfor %}
{% endblock %}

reports/templates/report/rating_list.html
{% extends "base.html" %}
{% block title %}rating{% endblock %}
{% block content %}

    <h1> Результаты тестирования</h1>

<form class="uniForm blueForms" action="" method="get">
        {{ filter.form.as_p }}
        <input class="btn btn-primary" type="submit" />
    </form>

<ul class="list-group">
{% for r in object_list %}
 <li class="list-group-item">{{r.survey}} {{r.created}} {{r.username}} -- {{r.count}}</li>
  {% empty %}
    <li>No rating yet.</li>
{% endfor %}
</ul>


<hr>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}
          <!-- If it ain't a search result display, don't append the search query
               to the URL. -->
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}&survey={{survey_id}}" tabindex="-1">Предыдущая</a>
          </li>
          {% else %}
          <!-- Append the searched query to the URL, so that on a search results page,
               the pagination don't revert to listing all the listview items. -->
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}&survey={{survey_id}}" tabindex="-1">Предыдущая</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Предыдущая</a>
        </li>
        {% endif %}

     {% for l in  page_obj.paginator.page_range %}
    {% if l <= page_obj.number|add:5 and l >= page_obj.number|add:-5 %}
        {% if page_obj.number == l %}
            <li class="page-item active"><a class="page-link" href="?page={{forloop.counter}}&survey={{survey_id}}">{{forloop.counter}}</a></li>
        {% else %}
           <li class="page-item"><a class="page-link" href="?page={{forloop.counter}}&survey={{survey_id}}">{{forloop.counter}}</a></li>
        {% endif %}
    {% endif %}
{% endfor %}

        {% if page_obj.has_next %}
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}&survey={{survey_id}}">Следующая</a>
          </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}&survey={{survey_id}}">Следующая</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Следующая</a>
        </li>
        {% endif %}
    </ul>
</nav>


<div>
    <a class="btn btn-primary"  href="{% url 'reports:xlsTofile' %}?survey={{survey_id}}">Сохранить в файл</a>
</div>



{% endblock %}