qwestion/urls.py
from django.urls import path
from . import views
app_name = 'qwestion'
urlpatterns = [
   # и т.д. пишешшь више чем нижняя строка
    path('', views.index, name='index'),
    path('s/<int:pk>/', views.start, name='survey-start'),
    path('survey/<int:pk>/', views.survey_view, name='survey_detail'),
    path('stop/', views.survey_stop, name='survey-stop'),
    path('pause/', views.pause, name='survey-pause'),
]

reports/urls.py
from django.urls import path
from . import views
from .views import RatingCountListView, RatingToXls

app_name = 'reports'
urlpatterns = [
    # path('', index, name='index'),
    path('', RatingCountListView.as_view(), name = 'rating-list'),
    path('xls/', RatingToXls.as_view(), name='xlsTofile'),

    ]

test_app/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls import include, url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('qwestion.urls', 'qwestion'), namespace='qwestion')),
    path('report/', include(('reports.urls', 'reports'), namespace='reports')),
    path('manager/', include(('screater.urls', 'screater'), namespace='screater')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

qwestion/models.py
from django.db import models
from django.contrib.auth.admin import User
from django.urls import reverse


class Survey(models.Model):
    title = models.CharField(max_length=255, verbose_name='Наименование теста')
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=' Автор')
    timedelta = models.IntegerField(default=0, verbose_name='Время выполнения теста')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    public = models.BooleanField(default=False, verbose_name="Опубликовано")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('qwestion:survey_detail', kwargs={"pk": self.id})

    class Meta:
        ordering = ['title', 'created']


class Qwestion(models.Model):
    Q_CHOICES = (
        ('ch', 'checkbox'),
        ('rd', 'radio'),
    )
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, verbose_name='Наименование теста')
    title = models.CharField(max_length=755, verbose_name='Вопрос')
    input = models.CharField(max_length=2, choices=Q_CHOICES, default='ch', verbose_name='Тип поля')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("qwestion:survey-start", kwargs={"pk": self.id})

    class Meta:
        ordering = ['pk']


class Answer(models.Model):
    qwestion = models.ForeignKey(Qwestion, on_delete=models.CASCADE, verbose_name='Вопрос')
    title = models.CharField(max_length=555, verbose_name='Ответ')
    truefild = models.BooleanField(default=False, verbose_name='Правильный ответ')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['pk']


class Rating(models.Model):
    username = models.CharField(max_length=55, db_index=True, verbose_name='Имя пользователя')
    email = models.CharField(max_length=55, verbose_name='Email')
    survey = models.ForeignKey(Survey, on_delete=models.PROTECT, verbose_name='Наменование теста')
    sessionid = models.CharField(max_length=200, db_index=True)
    qwestion = models.ForeignKey(Qwestion, on_delete=models.PROTECT, verbose_name='Вопрос')
    answer = models.CharField(max_length=100, verbose_name='Список номеров ответов пользователя')
    true_answer = models.CharField(max_length=100, verbose_name='Список номеров правильных ответов')
    result = models.BooleanField(default=False, verbose_name='Результат')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')

    def __str__(self):
        return self.sessionid

    class Meta:
        ordering = ['sessionid', '-created']

qwestion/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
# from django.core.signing import Signer
from .form import ContactForm
import uuid

import datetime

from .models import *


# Create your views here.


def index(request):
    """
    Список тестов
    :param request:
    :return:
    """
    survey = Survey.objects.filter(public=True)
    return render(request, 'qwestion/index.html', context={'survey': survey})


def pause(request):
    """
    Отсрочка ответа на вопрос
    :param request:
    :return:
    """
    if request.method == 'POST':
        qwestion_id = request.POST.get("qwestion_id")
        qwestions = list(request.session['qwestions'])
        qwestions.append(qwestion_id)
        qwestions.reverse()
        value = qwestions.pop()
        print(value)
        request.session['qwestions'] = qwestions
        request.session.modified = True

    return HttpResponseRedirect(reverse('qwestion:survey-start', kwargs={'pk': value}))


def start(request, pk):
    """
    Страница вопросов
    :param request:
    :param pk:
    :return:
    """
    if request.method == 'POST':
        sessionid = request.session['sessionkey']
        name = request.session['username']
        email = request.session['email']
        answers = [entry for entry in request.POST.values()][1:-2]
        answers = list(map(int, answers))
        survey_id = request.POST.get("survey_id")
        qwestion_id = request.POST.get("qwestion_id")
        answers_true = list(Answer.objects.filter(qwestion=qwestion_id, truefild=True).values_list('id', flat=True))
        if len(list(set(answers) ^ set(answers_true))) == 0:
            result = True
        else:
            result = False

        rating = Rating(username=name,email=email, survey=Survey.objects.get(pk=survey_id), sessionid=sessionid, qwestion=Qwestion.objects.get(pk=qwestion_id),
                        answer=answers,
                        true_answer=answers_true, result=result)
        rating.save()
        qwestions = list(request.session['qwestions'])
        if len(qwestions) == 0:
            #delete_session(request)
            return HttpResponseRedirect(reverse('qwestion:survey-stop'))

        else:
            value = qwestions.pop()
            request.session['qwestions'] = qwestions
            request.session.modified = True
            return HttpResponseRedirect(reverse('qwestion:survey-start', kwargs={'pk': value}))

    else:
        try:
            request.session['username']
        except:
            return HttpResponseRedirect(reverse('qwestion:index'))
        if stop_time(request):
            return HttpResponseRedirect(reverse('qwestion:survey-stop'))

            #return render(request, 'qwestion/stop.html', context={})
        qwestion = get_object_or_404(Qwestion, pk=pk)
        answers = Answer.objects.order_by('?').filter(qwestion=qwestion)
        mytimer = my_timer(request)
        return render(request, 'qwestion/start.html', context={'qwestion': qwestion, 'answers': answers, 'mytimer': mytimer})


def survey_view(request, pk):
    """
    Страница регистрации пользователей
    :param request:
    :param pk:
    :return:
    """
    form = ContactForm()
    if request.method == "GET":
        survey = get_object_or_404(Survey, pk=pk)
        return render(request, 'qwestion/survey_detail.html', {'survey': survey, 'form': form})

    if request.method == 'POST':
        request.session['username'] = request.POST.get("name")
        request.session['email'] = request.POST.get("email")
        request.session['timedelta'] = request.POST.get("timedelta")
        request.session['start_time'] = str(datetime.datetime.now())
        # signer = Signer()
        # request.session['sessionkey'] = signer.sign(request.POST.get("name") + ':' + request.POST.get("email") + ':' + str(datetime.datetime.now()))
        request.session['sessionkey'] = uuid.uuid4().hex
        survey_id = request.POST.get("surveyId")
        request.session['survey_id']  = survey_id
        qwestions = list(Qwestion.objects.order_by('?').filter(survey__id=survey_id).values_list('id', flat=True))
        value = qwestions.pop()
        request.session['qwestions'] = qwestions
        request.session.modified = True
        # return HttpResponse("UserName: {0} Qwestions: {1} value:{2}".format(request.session['username'], request.session['qwestion'], value))
        return HttpResponseRedirect(reverse('qwestion:survey-start', kwargs={'pk': value}))


def survey_stop(request):
    """
    Формируем последнюю страницу теста- результаты
    :param request:
    :return:
    """
    username = None
    try:

        survey_id = request.session['survey_id']
        sessionid = request.session['sessionkey']
        username =  request.session['username']


    except:
        # return render(request, 'qwestion/stop.html')
        pass

    survey = Survey.objects.get(pk=int(survey_id))
    countQwestion = Qwestion.objects.filter(survey=survey).count()
    rightAnswer = Rating.objects.filter(sessionid=sessionid,result=True).count()
    procent = rightAnswer/countQwestion*100

    delete_session(request)
    return render(request, 'qwestion/stop.html', context={'survey': survey, 'count': countQwestion, 'right': rightAnswer,'procent': procent,
                                                          'username':username})

def delete_session(request):
    """
    Удаляем данные сессии
    :param request:
    :return:
    """
    try:
        del request.session['qwestions']
        del request.session['username']
        del request.session['email']
        del request.session['timedelta']
        del request.session['start_time']
        del request.session['sessionid']
        del request.session['survey_id']
        del request.session['sessionkey']
        request.session.modified = True

    except KeyError:
        pass


def stop_time(request):
    try:
        timedelta = datetime.timedelta(minutes=int(request.session['timedelta']))
        start_time = datetime.datetime.strptime(request.session['start_time'], '%Y-%m-%d %H:%M:%S.%f')
        now = datetime.datetime.now()
        delta = start_time + timedelta

        if delta > now:
            return False
    except:
        return True
        # return render(request, 'qwestion/stop.html', context={})
    # return render(request, 'qwestion/stop.html', context={})
    return True


def my_timer(request):
    """
    Возвращаем время до окончания теста
    :param request:
    :return:
    """
    try:
        timedelta = datetime.timedelta(minutes=int(request.session['timedelta']))
        start_time = datetime.datetime.strptime(request.session['start_time'], '%Y-%m-%d %H:%M:%S.%f')
        now = datetime.datetime.now()
        delta = start_time + timedelta

        if delta > now:
            return delta
    except:
        return 0
        # return render(request, 'qwestion/stop.html', context={})
    # return render(request, 'qwestion/stop.html', context={})
    return 0

qwestion/templates/qwestion/index.html
{% extends "base.html" %}
{% block title %}index {% endblock %}
{% block content %}
    <h1> Выберите тест для сдачи</h1>
<ul class="list-group">
{% for s in survey %}
    <li class="list-group-item">
        <a href="{{s.get_absolute_url}}" class="stretched-link"> {{s.title}} </a>
    </li>
{% endfor %}
</ul>
{% endblock %}

qwestion/templates/qwestion/start.html
{% extends "base.html" %}
{% block title %}start {% endblock %}
{% load crispy_forms_tags %}
{% block counter %}
    {% include 'inc/countdown.html' %}
{% endblock %}
{% block content %}



<form  class="uniForm blueForms" method="POST">

    {% csrf_token %}

  <div class="form-group">
      <h3> {{qwestion.title}}</h3>
  </div>




        {% for a in answers %}
        <div class="form-group">

        <div class="form-check">
        <input class="form-check-input" type="{% if qwestion.input == 'rd' %}radio{% endif %}{% if qwestion.input == 'ch' %}checkbox{% endif %}" id="answerChoice1{{a.id}}" name="answer{% if qwestion.input == 'ch' %}{{a.id}}{% endif %}" value="{{a.id}}">
            <label class=" requiredField" for="answerChoice1{{a.id}}">
                {{a.title}}
            </label>

        </div>
        </div>
        {% endfor %}

    <div style='display:none'>
            <input type="hidden" name="survey_id" readonly value="{{qwestion.survey.id}}">
            <input type="hidden" name="qwestion_id" readonly value="{{qwestion.id}}">
    </div>
    <div class="buttonHolder">
        <button type="submit" class="btn btn-primary">Далее</button>
    </div>
</form>
<br>
<form  class="uniForm redForms" action="{% url 'qwestion:survey-pause' %}" method="POST">

    {% csrf_token %}
 <div class="buttonHolder">
        <input type="hidden" name="qwestion_id" readonly value="{{qwestion.id}}">
        <button type="submit" class="btn btn-primary">Пропустить вопрос</button>
    </div>
</form>
{% endblock %}

qwestion/templates/qwestion/stop.html
{% extends "base.html" %}
{% block title %}start {% endblock %}
{% block content %}
<div class="text-center">
<h3>Уважаемый {{username}}</h3><h3> тестирование на тему </h3>
<h1>{{survey}}</h1><h3> завершено !!!!!</h3>
<h1>Результаты тестирования : </h1>

<h3>Количество вопросов в тесте: {{count}}</h3>
<h3>Количество правильных ответов в тесте: {{right}}</h3>
<h3>Процент выполнения: {{procent}}%</h3>
</div>
{% endblock %}

qwestion/templates/qwestion/survey_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{survey.title}} {% endblock %}
{% block content %}
    <h1 class="mt-2"> {{survey.title}}</h1>
    <div><p>Время теста: {{survey.timedelta}} минут</p></div>

   {# Display a form #}
    <form  action="{{survey.get_absolute_url}}" method="post" >

   {% csrf_token %}
  {{form|crispy }}
    <input id="surveyId" name="surveyId" type="hidden" value="{{survey.id}}">
        <input id="timedelta" name="timedelta" type="hidden" value="{{survey.timedelta}}">
    <button type="submit" class="btn btn-success">
     Начать тестирование
    </button>


    </form>
{% endblock %}