qwestion/urls.py
from django.urls import path
from . import views
app_name = 'qwestion'
urlpatterns = [
   # и т.д. пишешшь више чем нижняя строка
    path('', views.index, name='index'),
    path('s/<int:pk>/', views.start, name='survey-start'),
    path('survey/<int:pk>/', views.survey_view, name='survey_detail'),
    path('stop/', views.survey_stop, name='survey-stop'),
    path('pause/', views.pause, name='survey-pause'),
]

reports/urls.py
from django.urls import path
from . import views
from .views import RatingCountListView, RatingToXls

app_name = 'reports'
urlpatterns = [
    # path('', index, name='index'),
    path('', RatingCountListView.as_view(), name = 'rating-list'),
    path('xls/', RatingToXls.as_view(), name='xlsTofile'),

    ]

screater/urls.py
from django.urls import path
from .views import *
app_name = 'screater'

urlpatterns = [
    path('', SurveyListView.as_view(), name='survey-list'),
    path('survey/<int:pk>/edit/', SurveyUpdateView.as_view(), name='survey-edit'),
    path('survey/new/', SurveyCreateView.as_view(), name='survey-new'),
    path('qwestion/', QwestionListView.as_view(), name='qwestion-list'),
    path('qwestion/<int:pk>/edit/', QwestionUpdateView.as_view(), name='qwestion-update'),
    path('qwestion/new/', QwestionCreateView.as_view(), name='qwestion-new'),
    path('qwestion/new/answers/', QwestionCreate.as_view(), name='qwestions-answers'),
    path('qwestion/<int:pk>/delete/', QwestionDeleteView.as_view(), name='qwestion-delete'),
    path('answer/', AnswerListView.as_view(), name='answer-list'),
    path('answer/new/', AnswerCreateView.as_view(), name='answer-new'),
    path('answer/<int:pk>/edit/', AnswerUpdateView.as_view(), name='answer-update'),
    path('answer/<int:pk>/delete/',AnswerDeleteView.as_view(), name='answer-delete'),

]

test_app/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from django.conf.urls import include, url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('qwestion.urls', 'qwestion'), namespace='qwestion')),
    path('report/', include(('reports.urls', 'reports'), namespace='reports')),
    path('manager/', include(('screater.urls', 'screater'), namespace='screater')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

qwestion/models.py
from django.db import models
from django.contrib.auth.admin import User
from django.urls import reverse


class Survey(models.Model):
    title = models.CharField(max_length=255, verbose_name='Наименование теста')
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=' Автор')
    timedelta = models.IntegerField(default=0, verbose_name='Время выполнения теста')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    public = models.BooleanField(default=False, verbose_name="Опубликовано")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('qwestion:survey_detail', kwargs={"pk": self.id})

    class Meta:
        ordering = ['title', 'created']


class Qwestion(models.Model):
    Q_CHOICES = (
        ('ch', 'checkbox'),
        ('rd', 'radio'),
    )
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, verbose_name='Наименование теста')
    title = models.CharField(max_length=755, verbose_name='Вопрос')
    input = models.CharField(max_length=2, choices=Q_CHOICES, default='ch', verbose_name='Тип поля')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("qwestion:survey-start", kwargs={"pk": self.id})

    class Meta:
        ordering = ['pk']


class Answer(models.Model):
    qwestion = models.ForeignKey(Qwestion, on_delete=models.CASCADE, verbose_name='Вопрос')
    title = models.CharField(max_length=555, verbose_name='Ответ')
    truefild = models.BooleanField(default=False, verbose_name='Правильный ответ')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['pk']


class Rating(models.Model):
    username = models.CharField(max_length=55, db_index=True, verbose_name='Имя пользователя')
    email = models.CharField(max_length=55, verbose_name='Email')
    survey = models.ForeignKey(Survey, on_delete=models.PROTECT, verbose_name='Наменование теста')
    sessionid = models.CharField(max_length=200, db_index=True)
    qwestion = models.ForeignKey(Qwestion, on_delete=models.PROTECT, verbose_name='Вопрос')
    answer = models.CharField(max_length=100, verbose_name='Список номеров ответов пользователя')
    true_answer = models.CharField(max_length=100, verbose_name='Список номеров правильных ответов')
    result = models.BooleanField(default=False, verbose_name='Результат')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')

    def __str__(self):
        return self.sessionid

    class Meta:
        ordering = ['sessionid', '-created']

qwestion/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
# from django.core.signing import Signer
from .form import ContactForm
import uuid

import datetime

from .models import *


# Create your views here.


def index(request):
    """
    Список тестов
    :param request:
    :return:
    """
    survey = Survey.objects.filter(public=True)
    return render(request, 'qwestion/index.html', context={'survey': survey})


def pause(request):
    """
    Отсрочка ответа на вопрос
    :param request:
    :return:
    """
    if request.method == 'POST':
        qwestion_id = request.POST.get("qwestion_id")
        qwestions = list(request.session['qwestions'])
        qwestions.append(qwestion_id)
        qwestions.reverse()
        value = qwestions.pop()
        print(value)
        request.session['qwestions'] = qwestions
        request.session.modified = True

    return HttpResponseRedirect(reverse('qwestion:survey-start', kwargs={'pk': value}))


def start(request, pk):
    """
    Страница вопросов
    :param request:
    :param pk:
    :return:
    """
    if request.method == 'POST':
        sessionid = request.session['sessionkey']
        name = request.session['username']
        email = request.session['email']
        answers = [entry for entry in request.POST.values()][1:-2]
        answers = list(map(int, answers))
        survey_id = request.POST.get("survey_id")
        qwestion_id = request.POST.get("qwestion_id")
        answers_true = list(Answer.objects.filter(qwestion=qwestion_id, truefild=True).values_list('id', flat=True))
        if len(list(set(answers) ^ set(answers_true))) == 0:
            result = True
        else:
            result = False

        rating = Rating(username=name,email=email, survey=Survey.objects.get(pk=survey_id), sessionid=sessionid, qwestion=Qwestion.objects.get(pk=qwestion_id),
                        answer=answers,
                        true_answer=answers_true, result=result)
        rating.save()
        qwestions = list(request.session['qwestions'])
        if len(qwestions) == 0:
            #delete_session(request)
            return HttpResponseRedirect(reverse('qwestion:survey-stop'))

        else:
            value = qwestions.pop()
            request.session['qwestions'] = qwestions
            request.session.modified = True
            return HttpResponseRedirect(reverse('qwestion:survey-start', kwargs={'pk': value}))

    else:
        try:
            request.session['username']
        except:
            return HttpResponseRedirect(reverse('qwestion:index'))
        if stop_time(request):
            return HttpResponseRedirect(reverse('qwestion:survey-stop'))

            #return render(request, 'qwestion/stop.html', context={})
        qwestion = get_object_or_404(Qwestion, pk=pk)
        answers = Answer.objects.order_by('?').filter(qwestion=qwestion)
        mytimer = my_timer(request)
        return render(request, 'qwestion/start.html', context={'qwestion': qwestion, 'answers': answers, 'mytimer': mytimer})


def survey_view(request, pk):
    """
    Страница регистрации пользователей
    :param request:
    :param pk:
    :return:
    """
    form = ContactForm()
    if request.method == "GET":
        survey = get_object_or_404(Survey, pk=pk)
        return render(request, 'qwestion/survey_detail.html', {'survey': survey, 'form': form})

    if request.method == 'POST':
        request.session['username'] = request.POST.get("name")
        request.session['email'] = request.POST.get("email")
        request.session['timedelta'] = request.POST.get("timedelta")
        request.session['start_time'] = str(datetime.datetime.now())
        # signer = Signer()
        # request.session['sessionkey'] = signer.sign(request.POST.get("name") + ':' + request.POST.get("email") + ':' + str(datetime.datetime.now()))
        request.session['sessionkey'] = uuid.uuid4().hex
        survey_id = request.POST.get("surveyId")
        request.session['survey_id']  = survey_id
        qwestions = list(Qwestion.objects.order_by('?').filter(survey__id=survey_id).values_list('id', flat=True))
        value = qwestions.pop()
        request.session['qwestions'] = qwestions
        request.session.modified = True
        # return HttpResponse("UserName: {0} Qwestions: {1} value:{2}".format(request.session['username'], request.session['qwestion'], value))
        return HttpResponseRedirect(reverse('qwestion:survey-start', kwargs={'pk': value}))


def survey_stop(request):
    """
    Формируем последнюю страницу теста- результаты
    :param request:
    :return:
    """
    username = None
    try:

        survey_id = request.session['survey_id']
        sessionid = request.session['sessionkey']
        username =  request.session['username']


    except:
        # return render(request, 'qwestion/stop.html')
        pass

    survey = Survey.objects.get(pk=int(survey_id))
    countQwestion = Qwestion.objects.filter(survey=survey).count()
    rightAnswer = Rating.objects.filter(sessionid=sessionid,result=True).count()
    procent = rightAnswer/countQwestion*100

    delete_session(request)
    return render(request, 'qwestion/stop.html', context={'survey': survey, 'count': countQwestion, 'right': rightAnswer,'procent': procent,
                                                          'username':username})

def delete_session(request):
    """
    Удаляем данные сессии
    :param request:
    :return:
    """
    try:
        del request.session['qwestions']
        del request.session['username']
        del request.session['email']
        del request.session['timedelta']
        del request.session['start_time']
        del request.session['sessionid']
        del request.session['survey_id']
        del request.session['sessionkey']
        request.session.modified = True

    except KeyError:
        pass


def stop_time(request):
    try:
        timedelta = datetime.timedelta(minutes=int(request.session['timedelta']))
        start_time = datetime.datetime.strptime(request.session['start_time'], '%Y-%m-%d %H:%M:%S.%f')
        now = datetime.datetime.now()
        delta = start_time + timedelta

        if delta > now:
            return False
    except:
        return True
        # return render(request, 'qwestion/stop.html', context={})
    # return render(request, 'qwestion/stop.html', context={})
    return True


def my_timer(request):
    """
    Возвращаем время до окончания теста
    :param request:
    :return:
    """
    try:
        timedelta = datetime.timedelta(minutes=int(request.session['timedelta']))
        start_time = datetime.datetime.strptime(request.session['start_time'], '%Y-%m-%d %H:%M:%S.%f')
        now = datetime.datetime.now()
        delta = start_time + timedelta

        if delta > now:
            return delta
    except:
        return 0
        # return render(request, 'qwestion/stop.html', context={})
    # return render(request, 'qwestion/stop.html', context={})
    return 0

qwestion/templates/inc/countdown.html
{% load static %} <!-- Instruct Django to load static files -->
{% load filter %}
<div class="countdown-block">
<h1 class="countdown-title">Время до окончания тестирования</h1>
<div id="countdown" class="countdown">
  <div class="countdown-number">
    <span class="hours countdown-time"></span>
    <span class="countdown-text">Часы</span>
  </div>
  <div class="countdown-number">
    <span class="minutes countdown-time"></span>
    <span class="countdown-text">Минуты</span>
  </div>
  <div class="countdown-number">
    <span class="seconds countdown-time"></span>
    <span class="countdown-text">Секунды</span>
  </div>
</div>
</div>
<script type="text/javascript"> var deadline = new Date({{ mytimer|dateWithZeroBasedMonth}}) </script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

qwestion/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg fixed-to">
  <a class="navbar-brand" href="{% url 'qwestion:index' %}">Тестирование</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'reports:rating-list' %}">Отчет по тестированию</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Тесты
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'screater:survey-list'%}">Список</a>
          <a class="dropdown-item" href="{%url 'screater:survey-new'%}">Добавить</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Вопросы
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'screater:qwestion-list'%}">Список</a>
          <a class="dropdown-item" href="{%url 'screater:qwestion-new'%}">Добавить</a>
          <a class="dropdown-item" href="{%url 'screater:qwestions-answers'%}">Добавить вопрос с 4 ответами</a>
        </div>
      </li>
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ответы
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'screater:answer-list'%}">Список</a>
          <a class="dropdown-item" href="{%url 'screater:answer-new'%}">Добавить</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Выход</a>
      </li>
    </ul>
  </div>
</nav>